version: "3"

services:
  db:
    image: postgres:16.1
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 123456
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./back
    volumes:
      - ./back:/usr/src/app
    ports:
      - 5000:5000
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./front
    volumes:
      - ./front:/usr/src/app
    ports:
      - 3000:3000
    depends_on:
      - backend

volumes:
  postgres: